#!/usr/bin/env bash

# Define paths. Users should modify these before running the script.
ODIN_PATH="PATH_TO_ODIN_REPO"
OLS_PATH="PATH_TO_ODIN_LSP_REPO"
LOG_PATH="PATH_TO_LOGFILE"

# LLVM command, modify if necessary.
LLVM_CMD="llvm-config-14"

# Clear the log file by truncating it.
> "$LOG_PATH"

# Function to pull and build from a repository.
pull_and_build() {
    local repo_path="$1"
    local build_cmd="$2"
    
    cd "$repo_path" || exit 1
    echo "Pulling latest from $(basename "$repo_path")..."
    git pull >>"$LOG_PATH" 2>&1
    echo "Building $(basename "$repo_path")..."
    $build_cmd >>"$LOG_PATH" 2>&1
}

pull_and_build "$ODIN_PATH" "LLVM_CONFIG=$LLVM_CMD ./build_odin.sh"
pull_and_build "$OLS_PATH" "./build.sh"
