#!/usr/bin/env bash

ODIN_PATH="PATH TO WHERE YOU CLONED THE ODIN REPO"
OLS_PATH="PATH TO WHERE YOU CLONED THE ODIN LSP REPO"
LOG_PATH="PATH TO WHERE YOU WANT THE LOGFILE"

# Change this to suit your system, if necessary
LLVM_CMD="llvm-config-14"

cd $ODIN_PATH
echo "Pulling latest Odin..."
git pull 1>$LOG_PATH 2>&1
echo "Building Odin..."
LLVM_CONFIG=$LLVM_CMD ./build_odin.sh 1>>$LOG_PATH 2>&1

cd $OLS_PATH
echo "Pulling latest OLS..."
git pull 1>>$LOG_PATH 2>&1
echo "Building OLS..."
./build.sh 1>>$LOG_PATH 2>&1